import React from "react";
import Head from "next/head";
import Header from "../../components/Header";
import Lists from "../../components/Lists";
import Form from "../../components/Form";

export default function Note() {
  return (
    <div>
      <Head>
        <title>memo-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full flex flex-col">
        <Header />
        <div className="flex h-5/6 ">
          <Lists />
          <Form />
        </div>
      </div>
    </div>
  );
}
