import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Lists from "../components/Lists";

export default function Index() {
  return (
    <div>
      <Head>
        <title>memo-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-h-screen w-full flex flex-col">
        <Header />
        <div className="flex flex-1 ">
          <Lists />
          <div className="w-2/3 border rounded-xl m-2.5">
            <h1>メモを選択してください</h1>
          </div>
        </div>
        <Footer />
      </div>
    </div>
  );
}
