import React from "react";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>memo-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="min-h-screen w-full flex flex-col">
        <header className="flex justify-between">
          <h1 className="font-bold text-4xl">MeMoApp</h1>
          <div>user-icon</div>
        </header>
        <div className="flex flex-1 ">
          <div className="w-1/3">メモ一覧</div>
          <div className="w-2/3">内容</div>
        </div>
        <footer>footer</footer>
      </body>
    </div>
  );
}
