import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Lists from "../components/Lists";
import Form from "../components/Form";

export default function Note() {
  return (
    <div>
      <Head>
        <title>memo-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen w-full flex flex-col">
        <Header />
        <div className="flex flex-1 ">
          <Lists />
          <Form />
        </div>
        <Footer />
      </div>
    </div>
  );
}
